@host = https://localhost:7125


### Cadastrar Pizza
POST {{host}}/sabor
Content-Type: application/json

{
  "sabor": "Napolitana",
  "tempoPreparo": 15,
  "preco": 10.3
}

### Cadastrar Estoque
POST {{host}}/estoque
Content-Type: application/json

{
  "pizzaId": 2,
  "quantidade": 100
}

### Reduzir Estoque
PUT {{host}}/estoque/pizza/{{2}}/{{100}}